apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitlio-ingress
  namespace: fitlio
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - fitlio-jay.duckdns.org
      secretName: fitlio-tls
  rules:
    - host: fitlio-jay.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8000
