apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fitlio-ingress
  namespace: fitlio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: traefik
  rules:
  - host: fitlio-jay.duckdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000
