apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: monitoring
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
    clients:
      - url: https://logs-prod-026.grafana.net/loki/api/v1/push
        basic_auth:
          username: "1589299"
          password_file: /etc/promtail/token
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: fitlio
        static_configs:
          - targets:
              - localhost
            labels:
              job: fitlio
              namespace: fitlio
              __path__: /var/log/containers/*_fitlio_*.log
