"""add_language_column_to_members

Revision ID: c35cb850a20c
Revises: 9e1863cf8d43
Create Date: 2026-05-01 12:06:44.024700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35cb850a20c'
down_revision: Union[str, Sequence[str], None] = '9e1863cf8d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'language')
    # ### end Alembic commands ###
