server {
    listen 80;
    server_name fitlio-jay.duckdns.org;

    location /auth/ {
        proxy_pass http://api:8000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }

    location /classes/ {
        proxy_pass http://api:8000/classes/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }

    location /payments/ {
        proxy_pass http://api:8000/payments/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri.html $uri/ =404;
    }
}