server {
    listen 80;
    server_name fitlio-jay.duckdns.org;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name fitlio-jay.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/fitlio-jay.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/fitlio-jay.duckdns.org/privkey.pem;

    location /auth/ {
        proxy_pass http://api:8000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }
    location /classes {
        proxy_pass http://api:8000/classes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }
    location /payments/ {
        proxy_pass http://api:8000/payments/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }
    location /check-in {
        proxy_pass http://api:8000/check-in;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }
    location /attendances {
        proxy_pass http://api:8000/attendances;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        add_header Access-Control-Allow-Origin *;
    }
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri.html $uri/ =404;
    }
}