apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgres.env.db }}
        - name: POSTGRES_USER
          value: {{ .Values.postgres.env.user }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fitlio-env
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: postgres
  ports:
  - port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.service.port }}x
